mostly cleaned up, still seeing the error in the extended description after getting rid of batch size in the fit_generator function
 python3 hyperParamScan_Mary_June2020.py 
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0610 13:47:06.733547 139640976516928 deprecation.py:506] From /cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
training_generator is: <my_classes.DataGenerator object at 0x7f006b3100d0>
validation_generator is: <my_classes.DataGenerator object at 0x7f006b2a66d0>
training_generator.dim is: 8
validation_generator.dim is: 8
training_generator.num_of_labels is: 3
2020-06-10 13:47:08.251029: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999995000 Hz
2020-06-10 13:47:08.251553: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5fd74d0 executing computations on platform Host. Devices:
2020-06-10 13:47:08.251598: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-06-10 13:47:08.343819: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
18/18 [==============================] - 2s 88ms/step - loss: 1.1906 - val_loss: 0.3307
3
8
x parameters are
[[1.00000000e+00 0.00000000e+00 2.80000000e+01 5.00000000e+00
  1.77466802e-01 5.00000000e+02]]
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 8)]               0         
_________________________________________________________________
batch_normalization (BatchNo (None, 8)                 32        
_________________________________________________________________
dropout_6 (Dropout)          (None, 8)                 0         
_________________________________________________________________
final_output (Dense)         (None, 3)                 27        
=================================================================
Total params: 59
Trainable params: 43
Non-trainable params: 16
_________________________________________________________________
Traceback (most recent call last):
  File "hyperParamScan_Mary_June2020.py", line 166, in <module>
    opt_model = GPyOpt.methods.BayesianOptimization(f=f, domain=bounds)
  File "/uscms/home/mhadley/nobackup/BayOptCode/.local/lib/python3.7/site-packages/GPyOpt/methods/bayesian_optimization.py", line 119, in __init__
    self._init_design_chooser()
  File "/uscms/home/mhadley/nobackup/BayOptCode/.local/lib/python3.7/site-packages/GPyOpt/methods/bayesian_optimization.py", line 195, in _init_design_chooser
    self.Y, _ = self.objective.evaluate(self.X)
  File "/uscms/home/mhadley/nobackup/BayOptCode/.local/lib/python3.7/site-packages/GPyOpt/core/task/objective.py", line 50, in evaluate
    f_evals, cost_evals = self._eval_func(x)
  File "/uscms/home/mhadley/nobackup/BayOptCode/.local/lib/python3.7/site-packages/GPyOpt/core/task/objective.py", line 74, in _eval_func
    rlt = self.func(np.atleast_2d(x[i]))
  File "hyperParamScan_Mary_June2020.py", line 159, in f
    labels = n_labels
  File "hyperParamScan_Mary_June2020.py", line 130, in run_model
    model_evaluation = _model.model_evaluate()
  File "hyperParamScan_Mary_June2020.py", line 118, in model_evaluate
    self.model_fit()
  File "hyperParamScan_Mary_June2020.py", line 114, in model_fit
    TerminateOnNaN()]) 
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 219, in model_iteration
    while step < target_steps:
TypeError: '<' not supported between instances of 'int' and 'DataGenerator'